<?php

namespace Nabcellent\Kyanda\Tests;

use GuzzleHttp\Client;
use GuzzleHttp\Handler\MockHandler;
use GuzzleHttp\HandlerStack;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Config;
use Nabcellent\Kyanda\Library\BaseClient;

/**
 * Class TestCase
 * @package Nabcellent\Tests
 */
abstract class MockServerTestCase extends TestCase
{
    use RefreshDatabase;

    protected BaseClient $_client;

    protected MockHandler $mock;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        Config::set('kyanda.urls.base', '/');
        Config::set('kyanda.api_key', 'somethinggoeshere');
        Config::set('kyanda.merchant_id', 'somethinggoeshere');

        $this->mock = new MockHandler();

        $handlerStack = HandlerStack::create($this->mock);
        $this->_client = new BaseClient(new Client(['handler' => $handlerStack]));
    }

    protected array $mockResponses = [
        'balance' => [
            'Account_Bal' => 399930,
            'Earnings_Bal' => 1586.6
        ],
        'transaction_status' => [
            'status' => '200',
            'details' => [
                'Category' => 'BankPayout',
                'source' => 'PaymentWallet',
                'Phone' => '2042581154',
                'MerchantID' => 'kyanda',
                'details' => [],
                'Status' => 'Success',
                'status_code' => '0000',
                'message' => 'Your request has been processed.',
                'Posted_Time' => '23-05-2021 10:29 pm',
                'transactionFee' => '50',
                'transactionRef' => 'KYAAPI677833',
                'Amount' => '1500'
            ]
        ],
        'query_transaction_status' => [
            'status' => '0000',
            'details' => [
                'Category' => 'BankPayout',
                'source' => 'PaymentWallet',
                'Phone' => '213220',
                'MerchantID' => 'kyanda',
                'details' => [],
                'Status' => 'Success',
                'status_code' => '0000',
                'message' => 'Your request has been processed.',
                'Posted_Time' => '23-05-2021 10:29 pm',
//                'transactionFee' => '50',
                'transactionRef' => 'KYAAPI677833',
                'Amount' => '1500'
            ]
        ],
        'request_success' => [
            "status" => "Success",
            "status_code" => "0000",
            "merchant_reference" => "KYAAPI165394",
            "transactiontxt" => "Your request has been posted successfully!"
        ],
        'request_failed' => [
            "status" => "Failed",
            "status_code" => "5000",
            "transactiontxt" => "Unexpected error has occurred."
        ],
        'query_transaction_status_failed' => [
            'status' => '1102',
            'details' => [
                'Category' => 'BankPayout',
                'source' => 'PaymentWallet',
                'Phone' => '2042581154',
                'MerchantID' => 'kyanda',
                'details' => [],
                'Status' => 'Failed',
                'status_code' => '1101',
                'message' => 'Your request has been processed.',
                'Posted_Time' => '23-05-2021 10:29 pm',
                'transactionFee' => '50',
                'transactionRef' => 'KYAAPI677834',
                'Amount' => '1500'
            ]
        ],
        'query_transaction_status_failed_2' => [
            'status' => '1102',
            'details' => [
                'Category' => 'BankPayout',
                'source' => 'PaymentWallet',
                'Phone' => '2042581154',
                'MerchantID' => 'kyanda',
                'details' => [],
                'Status' => 'Success',
                'status_code' => 'Success',
                'message' => 'Your request has been processed.',
                'Posted_Time' => '23-05-2021 10:29 pm',
                'transactionRef' => 'KYAAPI677835',
                'Amount' => '1500'
            ]
        ],
    ];
}
