<?php

namespace Nabcellent\Kyanda\Tests\Repositories;

use GuzzleHttp\Psr7\Response;
use Nabcellent\Kyanda\Library\Providers;
use Nabcellent\Kyanda\Models\KyandaRequest;
use Nabcellent\Kyanda\Models\KyandaTransaction;
use Nabcellent\Kyanda\Repositories\Kyanda;
use Nabcellent\Kyanda\Tests\MockServerTestCase;

class KyandaTest extends MockServerTestCase
{

    private Kyanda $repository;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->repository = new Kyanda($this->_client);
    }

    /** @test */
    function query_transaction_statuses()
    {
        KyandaRequest::create([
            'status_code' => '0000',
            'status' => 'Success',
            'merchant_reference' => 'KYAAPI677833',
            'provider' => Providers::SAFARICOM,
            'message' => 'Your request has been posted successfully!'
        ]);

        KyandaRequest::create([
            'status_code' => '0000',
            'status' => 'Success',
            'merchant_reference' => 'KYAAPI677834',
            'provider' => Providers::SAFARICOM,
            'message' => 'Your request has been posted successfully!'
        ]);

        $this->mock->append(
            new Response(200, ['Content_type' => 'application/json'],
                json_encode($this->mockResponses['query_transaction_status'])));
        $this->mock->append(
            new Response(200, ['Content_type' => 'application/json'],
                json_encode($this->mockResponses['query_transaction_status_failed'])));

        $res = $this->repository->queryTransactionStatus();

        $transaction = KyandaTransaction::whereTransactionReference("KYAAPI677833")->first();

        $this->assertEquals($res['successful']['KYAAPI677833'], $transaction->status);
    }

    /** @test */
    function query_failed_transaction_status()
    {

        KyandaRequest::create([
            'status_code' => '0000',
            'status' => 'Success',
            'merchant_reference' => 'KYAAPI677835',
            'provider' => Providers::SAFARICOM,
            'message' => 'Your request has been posted successfully!'
        ]);

        $this->mock->append(
            new Response(200, ['Content_type' => 'application/json'],
                json_encode($this->mockResponses['query_transaction_status_failed_2'])));

        $res = $this->repository->queryTransactionStatus();

        $transaction = KyandaTransaction::whereTransactionReference("KYAAPI677835")->first();

        $this->assertEquals($res['successful']['KYAAPI677835'], $transaction->status);
    }


    /** @test */
    function query_transaction_statuses_server_error()
    {
        KyandaRequest::create([
            'status_code' => '0000',
            'status' => 'Success',
            'merchant_reference' => 'KYAAPI677833',
            'provider' => Providers::SAFARICOM,
            'message' => 'Your request has been posted successfully!'
        ]);

        $this->mock->append(
            new Response(404, ['Content_type' => 'application/json'],
                json_encode($this->mockResponses['query_transaction_status'])));

        $res = $this->repository->queryTransactionStatus();

        $this->assertIsString($res['errors']['KYAAPI677833']);
    }
}